@baseUrl = http://localhost:5076
@route = api/v1/auth
@no-redirect = true
@no-cookie-jar = false


### CREATE USER ACCOUNT

POST {{baseUrl}}/{{route}}/create-user
Content-Type: application/json

{
    "name": "Test User Name",
    "surname": "Test User Surname",
    "email": "user@system.com",
    "identityNumber": "12345678901",
    "city": "Istanbul",
    "country": "TR",
    "zipCode": "34343",
    "address": "Istanbul, TR",
    "password": "UserPassword123!",
    "phoneNumber": "9876543210",
    "dateOfBirth": "1999-03-24"
}

### CREATE ADMIN ACCOUNT

POST {{baseUrl}}/{{route}}/create-admin
Content-Type: application/json

{
    "name": "Test Admin Name",
    "surname": "Test Admin Surname",
    "email": "admin@system.com",
    "identityNumber": "12345678901",
    "city": "Istanbul",
    "country": "TR",
    "zipCode": "34343",
    "address": "Istanbul, TR",
    "password": "AdminPassword123!",
    "phoneNumber": "9876543210",
    "dateOfBirth": "1980-01-01"
}

### LOGIN USER ACCOUNT
# @name loginUser
POST {{baseUrl}}/{{route}}/login
Content-Type: application/json

{
  "email": "user@system.com",  
  "password": "UserPassword123!"
}

### LOGIN ADMIN ACCOUNT
# @name loginAdmin
POST {{baseUrl}}/{{route}}/login
Content-Type: application/json

{
  "email": "admin@system.com",  
  "password": "AdminPassword123!"
}

### LOGOUT
POST {{baseUrl}}/{{route}}/logout

### REFRESH TOKEN USER
POST {{baseUrl}}/{{route}}/refresh-token
