@baseUrl = http://localhost:5076
@route = api/v1/notifications
@USER_TOKEN = {{$dotenv USER_TOKEN}}
@ADMIN_TOKEN = {{$dotenv ADMIN_TOKEN}}
@NOTIFICATION_ID = 1

### GET NOTIFICATIONS (USER)
GET {{baseUrl}}/{{route}}
Authorization: Bearer {{USER_TOKEN}}

### GET NOTIFICATIONS (ADMIN)
GET {{baseUrl}}/{{route}}
Authorization: Bearer {{ADMIN_TOKEN}}

### GET UNREAD NOTIFICATIONS (USER)
GET {{baseUrl}}/{{route}}/unread
Authorization: Bearer {{USER_TOKEN}}

### GET UNREAD NOTIFICATIONS (ADMIN)
GET {{baseUrl}}/{{route}}/unread
Authorization: Bearer {{ADMIN_TOKEN}}

### GET UNREAD NOTIFICATIONS COUNT (USER)
GET {{baseUrl}}/{{route}}/unread-count
Authorization: Bearer {{USER_TOKEN}}

### GET UNREAD NOTIFICATIONS COUNT (ADMIN)
GET {{baseUrl}}/{{route}}/unread-count
Authorization: Bearer {{ADMIN_TOKEN}}

### MARK NOTIFICATION AS READ (USER)
POST {{baseUrl}}/{{route}}/{{NOTIFICATION_ID}}/mark-read
Authorization: Bearer {{USER_TOKEN}}

### MARK NOTIFICATION AS READ (ADMIN)
POST {{baseUrl}}/{{route}}/{{NOTIFICATION_ID}}/mark-read
Authorization: Bearer {{ADMIN_TOKEN}}

### MARK ALL NOTIFICATIONS AS READ (USER)
POST {{baseUrl}}/{{route}}/mark-all-read
Authorization: Bearer {{USER_TOKEN}}

### MARK ALL NOTIFICATIONS AS READ (ADMIN)
POST {{baseUrl}}/{{route}}/mark-all-read
Authorization: Bearer {{ADMIN_TOKEN}}

### DELETE NOTIFICATION (USER)
DELETE {{baseUrl}}/{{route}}/{{NOTIFICATION_ID}}
Authorization: Bearer {{USER_TOKEN}}

### DELETE NOTIFICATION (ADMIN)
DELETE {{baseUrl}}/{{route}}/{{NOTIFICATION_ID}}
Authorization: Bearer {{ADMIN_TOKEN}}