# @name Using development environment
# @environment development

@baseUrl = http://localhost:5076
@adminToken = {{$dotenv ADMIN_TOKEN}}

### GET ALL PRODUCTS

GET {{baseUrl}}/api/admin/products
Authorization: Bearer {{adminToken}}

### GET PRODUCT BY ID

GET {{baseUrl}}/api/admin/products/2
Authorization: Bearer {{adminToken}}

### CREATE PRODUCT

POST {{baseUrl}}/api/admin/products/create
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "Name": "Dyson V11",
  "Description": "Dyson V11 is a vacuum cleaner that is the latest in the Dyson series",
  "Price": 1099.99,
  "StockQuantity": 100,
  "DiscountRate": 10,
  "ImageUrl": "https://via.placeholder.com/135",
  "CategoryId": 3
}

### UPDATE PRODUCT BY ID

PUT {{baseUrl}}/api/admin/products/update/1
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "Name": "Samsung S22",
  "Description": "Samsung S22 is a smartphone that is the latest in the Samsung series",
  "Price": 499.99,
  "StockQuantity": 3,
  "DiscountRate": 5,
  "ImageUrl": "https://via.placeholder.com/150",
  "CategoryId": 1
}

### DELETE PRODUCT BY ID

DELETE {{baseUrl}}/api/admin/products/delete/2
Authorization: Bearer {{adminToken}}