# @name Using development environment
# @environment development

@baseUrl = http://localhost:5076
@adminToken = {{$dotenv ADMIN_TOKEN}}

### GET ALL PRODUCTS

GET {{baseUrl}}/api/admin/products
Authorization: Bearer {{adminToken}}

### GET PRODUCT BY ID

GET {{baseUrl}}/api/admin/products/1
Authorization: Bearer {{adminToken}}

### CREATE PRODUCT

POST {{baseUrl}}/api/admin/products/create
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "Name": "Playstation 5",
  "Description": "Playstation 5 is a gaming console that is the latest in the Playstation series",
  "Price": 499.99,
  "StockQuantity": 300,
  "DiscountRate": 13,
  "ImageUrl": "https://via.placeholder.com/150"
}

### UPDATE PRODUCT BY ID

PUT {{baseUrl}}/api/admin/products/update/1
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "Name": "Xbox Series X",
  "Description": "Xbox Series X is a gaming console that is the latest in the Xbox series",
  "Price": 499.99,
  "StockQuantity": 3,
  "DiscountRate": 5,
  "ImageUrl": "https://via.placeholder.com/150"
}

### DELETE PRODUCT BY ID

DELETE {{baseUrl}}/api/admin/products/delete/1
Authorization: Bearer {{adminToken}}