# @name Using development environment
# @environment development

@baseUrl = http://localhost:5076
@adminToken = {{$dotenv ADMIN_TOKEN}}

### GET ALL ACCOUNTS

GET {{baseUrl}}/api/admin/accounts
Authorization: Bearer {{adminToken}}

### GET ACCOUNT BY ID

GET {{baseUrl}}/api/admin/accounts/1
Authorization: Bearer {{adminToken}}

### DELETE ACCOUNT BY ID

DELETE {{baseUrl}}/api/admin/accounts/delete/1
Authorization: Bearer {{adminToken}}

### REVOKE USER TOKEN

POST {{baseUrl}}/api/admin/accounts/revoke-token
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "email": "bsn.mehmetcanari@gmail.com"
}

### BAN ACCOUNT

POST {{baseUrl}}/api/admin/accounts/ban
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "email": "bsn.mehmetcanari@gmail.com",
    "until": "2025-07-11",
    "reason": "Test"
}

### UNBAN ACCOUNT

POST {{baseUrl}}/api/admin/accounts/unban
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "email": "bsn.mehmetcanari@gmail.com"
}



