@baseUrl = http://localhost:5076

### GET ALL PRODUCTS

GET {{baseUrl}}/api/admin/products
Authorization: Bearer {{ADMIN_TOKEN}}

### GET PRODUCT BY ID

GET {{baseUrl}}/api/admin/products/1
Authorization: Bearer {{ADMIN_TOKEN}}

### CREATE PRODUCT

POST {{baseUrl}}/api/admin/products/create
Content-Type: application/json
Authorization: Bearer {{ADMIN_TOKEN}}

{
  "Name": "Playstation 5",
  "Description": "Playstation 5 is a gaming console that is the latest in the Sony series",
  "Price": 499.99,
  "StockQuantity": 10,
  "DiscountRate": 0,
  "ImageUrl": "https://via.placeholder.com/135",
  "CategoryId": 1
}

### UPDATE PRODUCT BY ID

PUT {{baseUrl}}/api/admin/products/update/1
Content-Type: application/json
Authorization: Bearer {{ADMIN_TOKEN}}

{
  "Name": "Playstation 5",
  "Description": "Playstation 5 is a gaming console that is the latest in the Sony series",
  "Price": 499.99,
  "StockQuantity": 10,
  "DiscountRate": 25,
  "ImageUrl": "https://via.placeholder.com/135",
  "CategoryId": 1
}

### DELETE PRODUCT BY ID

DELETE {{baseUrl}}/api/admin/products/delete/1
Authorization: Bearer {{ADMIN_TOKEN}}