@baseUrl = http://localhost:5076/
@route = api/admin/orders
### GET ALL ORDERS

GET {{baseUrl}}{{route}}
Authorization: Bearer {{ADMIN_TOKEN}}

### GET ORDER BY ID

GET {{baseUrl}}{{route}}/1
Authorization: Bearer {{ADMIN_TOKEN}}

### DELETE ORDER BY ID

DELETE {{baseUrl}}{{route}}/delete/1
Authorization: Bearer {{ADMIN_TOKEN}}

### UPDATE ORDER STATUS BY ID

PUT {{baseUrl}}{{route}}/update/1
Content-Type: application/json
Authorization: Bearer {{ADMIN_TOKEN}}

{
    "Status": 1
}
