@baseUrl = http://localhost:5076
@route = api/admin/categories

### CREATE CATEGORY

POST {{baseUrl}}/{{route}}/create
Authorization: Bearer {{ADMIN_TOKEN}}
Content-Type: application/json

{
    "name": "Electronics",
    "description": "Electronics category"
}

### GET CATEGORY BY ID

GET {{baseUrl}}/{{route}}/1
Authorization: Bearer {{ADMIN_TOKEN}}

### UPDATE CATEGORY

PUT {{baseUrl}}/{{route}}/update/1
Authorization: Bearer {{ADMIN_TOKEN}}
Content-Type: application/json

{
    "name": "Updated Electronics",
    "description": "Updated Electronics category"
}

### DELETE CATEGORY

DELETE {{baseUrl}}/{{route}}/delete/2
Authorization: Bearer {{ADMIN_TOKEN}}
