@baseUrl = http://localhost:5076
@route = api/v1/admin/accounts
### GET ALL ACCOUNTS

GET {{baseUrl}}/{{route}}
Authorization: Bearer {{ADMIN_TOKEN}}

### GET ACCOUNT BY ID

GET {{baseUrl}}/{{route}}/1
Authorization: Bearer {{ADMIN_TOKEN}}

### DELETE ACCOUNT BY ID

DELETE {{baseUrl}}/{{route}}/delete/1
Authorization: Bearer {{ADMIN_TOKEN}}

### REVOKE USER TOKEN

POST {{baseUrl}}/{{route}}/revoke-token
Authorization: Bearer {{ADMIN_TOKEN}}
Content-Type: application/json

{
    "email": "bsn.mehmetcanari@gmail.com"
}

### BAN ACCOUNT

POST {{baseUrl}}/{{route}}/ban
Authorization: Bearer {{ADMIN_TOKEN}}
Content-Type: application/json

{
    "email": "bsn.mehmetcanari@gmail.com",
    "until": "2025-07-11",
    "reason": "Test"
}

### UNBAN ACCOUNT

POST {{baseUrl}}/api/v1/admin/accounts/unban
Authorization: Bearer {{ADMIN_TOKEN}}
Content-Type: application/json

{
    "email": "bsn.mehmetcanari@gmail.com"
}



