@baseUrl = http://localhost:5076
@route = api/auth
@no-redirect = true
@no-cookie-jar = false

### CREATE USER ACCOUNT

POST {{baseUrl}}/{{route}}/create-user
Content-Type: application/json

{
    "fullName": "Mehmet Can Ari",
    "email": "bsn.mehmetcan@gmail.com",
    "password": "1examplePassword@MehmetCan",
    "address": "Istanbul, TR",
    "phoneNumber": "1234567890",
    "dateOfBirth": "1999-03-24"
}

### CREATE ADMIN ACCOUNT

POST {{baseUrl}}/{{route}}/create-admin
Content-Type: application/json

{
    "fullName": "Admin",
    "email": "admin@system.com",
    "password": "AdminPassword123!",
    "address": "Istanbul, TR",
    "phoneNumber": "9876543210",
    "dateOfBirth": "1980-01-01"
}

### LOGIN USER ACCOUNT
# @name loginUser
POST {{baseUrl}}/{{route}}/login
Content-Type: application/json

{
  "email": "bsn.mehmetcan@gmail.com",  
  "password": "1examplePassword@MehmetCan"
}

### LOGIN ADMIN ACCOUNT
# @name loginAdmin
POST {{baseUrl}}/{{route}}/login
Content-Type: application/json

{
  "email": "admin@system.com",  
  "password": "AdminPassword123!"
}

### REFRESH TOKEN USER
POST {{baseUrl}}/{{route}}/refresh-token
