@baseUrl = http://localhost:5076
@route = api/auth
@no-redirect = true
@no-cookie-jar = false
@accessToken = {{loginUser.response.body.$.authResponse.accessToken}}


### CREATE USER ACCOUNT

POST {{baseUrl}}/{{route}}/create-user
Content-Type: application/json

{
    "fullName": "User",
    "email": "user@system.com",
    "password": "UserPassword123!",
    "address": "Istanbul, TR",
    "phoneNumber": "1234567890",
    "dateOfBirth": "1999-03-24"
}

### CREATE ADMIN ACCOUNT

POST {{baseUrl}}/{{route}}/create-admin
Content-Type: application/json

{
    "fullName": "Admin",
    "email": "admin@system.com",
    "password": "AdminPassword123!",
    "address": "Istanbul, TR",
    "phoneNumber": "9876543210",
    "dateOfBirth": "1980-01-01"
}

### LOGIN USER ACCOUNT
# @name loginUser
POST {{baseUrl}}/{{route}}/login
Content-Type: application/json

{
  "email": "user@system.com",  
  "password": "UserPassword123!"
}

### LOGIN ADMIN ACCOUNT
# @name loginAdmin
POST {{baseUrl}}/{{route}}/login
Content-Type: application/json

{
  "email": "admin@system.com",  
  "password": "AdminPassword123!"
}

### LOGOUT USER
POST {{baseUrl}}/{{route}}/logout
Authorization: Bearer {{accessToken}}

### REFRESH TOKEN USER
POST {{baseUrl}}/{{route}}/refresh-token
