@baseUrl = http://localhost:5076

### GET PROFILE AS USER
GET {{baseUrl}}/api/account/profile
Authorization: Bearer {{USER_TOKEN}}

### GET PROFILE AS ADMIN
GET {{baseUrl}}/api/account/profile
Authorization: Bearer {{ADMIN_TOKEN}}

