@baseUrl = http://localhost:5076
@userToken = {{$dotenv.USER_TOKEN}}
@adminToken = {{$dotenv.ADMIN_TOKEN}}

### GET PROFILE AS USER
GET {{baseUrl}}/api/account/profile
Authorization: Bearer {{userToken}}

### GET PROFILE AS ADMIN
GET {{baseUrl}}/api/account/profile
Authorization: Bearer {{adminToken}}

