@baseUrl = http://localhost:5076
@route = api/v1/admin/products
@ADMIN_TOKEN = {{$dotenv ADMIN_TOKEN}}
### GET ALL PRODUCTS

GET {{baseUrl}}/{{route}}
Authorization: Bearer {{ADMIN_TOKEN}}

### GET PRODUCT BY ID

GET {{baseUrl}}/{{route}}/1
Authorization: Bearer {{ADMIN_TOKEN}}

### CREATE PRODUCT

POST {{baseUrl}}/{{route}}/create
Content-Type: application/json
Authorization: Bearer {{ADMIN_TOKEN}}

{
  "Name": "Playstation 5",
  "Description": "Playstation 5 is a gaming console that is the latest in the Sony series",
  "Price": 499.99,
  "StockQuantity": 200,
  "DiscountRate": 3,
  "ImageUrl": "https://mehmetcanari-ecommerce-products.s3.eu-central-1.amazonaws.com/products/05792688-9d02-48fe-8ca2-7f9424cb2f5c_playstation5.jpeg",
  "CategoryId": 1
}

### UPLOAD IMAGE

POST {{baseUrl}}/{{route}}/upload-image
Content-Type: multipart/form-data
Authorization: Bearer {{ADMIN_TOKEN}}


### UPDATE PRODUCT BY ID

PUT {{baseUrl}}/{{route}}/update/1
Content-Type: application/json
Authorization: Bearer {{ADMIN_TOKEN}}

{
  "Name": "Playstation 5",
  "Description": "Playstation 5 is a gaming console that is the latest in the Sony series",
  "Price": 499.99,
  "StockQuantity": 2000,
  "DiscountRate": 0,
  "ImageUrl": "https://via.placeholder.com/135",
  "CategoryId": 1
}

### DELETE PRODUCT BY ID

DELETE {{baseUrl}}/{{route}}/delete/1
Authorization: Bearer {{ADMIN_TOKEN}}