@baseUrl = http://localhost:5076
@resource = orders

###
POST {{baseUrl}}/{{resource}}
Content-Type: application/json

{
    "orderItem": {
        "id": 1
    }
}

###
GET {{baseUrl}}/{{resource}}

###
GET {{baseUrl}}/{{resource}}/1

###
PUT {{baseUrl}}/{{resource}}/1
Content-Type: application/json

{
    "orderItem": {
        "id": 1
    }
}