# @name Using development environment
# @environment development

@baseUrl = http://localhost:5076
@adminToken = {{$dotenv ADMIN_TOKEN}}

### GET ALL PRODUCTS

GET {{baseUrl}}/api/admin/products
Authorization: Bearer {{adminToken}}

### GET PRODUCT BY ID

GET {{baseUrl}}/api/admin/products/1
Authorization: Bearer {{adminToken}}

### CREATE PRODUCT

POST {{baseUrl}}/api/admin/products/create
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "Name": "Xbox Series X",
  "Description": "Xbox Series X is a gaming console that is the latest in the Xbox series",
  "Price": 499.99,
  "StockQuantity": 300,
  "DiscountRate": 5
}

### UPDATE PRODUCT BY ID

PUT {{baseUrl}}/api/admin/products/update/1
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "Name": "High-End Gaming PC",
  "Description": "A gaming PC with high-end specs",
  "Price": 2999.99,
  "ImageUrl": "exampleURL",
  "StockQuantity": 3
}

### DELETE PRODUCT BY ID

DELETE {{baseUrl}}/api/admin/products/delete/1
Authorization: Bearer {{adminToken}}