# @name Using development environment
# @environment development

@baseUrl = http://localhost:5076
@adminToken = {{$dotenv ADMIN_TOKEN}}

### GET ALL ACCOUNTS

GET {{baseUrl}}/api/admin/accounts
Authorization: Bearer {{adminToken}}

### GET ACCOUNT BY ID

GET {{baseUrl}}/api/admin/accounts/1
Authorization: Bearer {{adminToken}}

### DELETE ACCOUNT BY ID

DELETE {{baseUrl}}/api/admin/accounts/delete/1
Authorization: Bearer {{adminToken}}
