@baseUrl = http://localhost:5076
@userToken = {{$dotenv.USER_TOKEN}}

### GET ALL PRODUCTS

GET {{baseUrl}}/api/user/products
Authorization: Bearer {{userToken}}

### GET PRODUCT BY ID

GET {{baseUrl}}/api/user/products/1
Authorization: Bearer {{userToken}}

