@baseUrl = http://localhost:5076/
@route = api/user/basket
@userToken = {{$dotenv.USER_TOKEN}}

### CREATE ORDER ITEM
POST {{baseUrl}}{{route}}/create
Content-Type: application/json
Authorization: Bearer {{userToken}}

{
  "ProductId": 1,
  "Quantity": 1
}

### UPDATE ORDER ITEM
PUT {{baseUrl}}{{route}}/update
Content-Type: application/json
Authorization: Bearer {{userToken}}

{
  "BasketItemId": 1,
  "ProductId": 1,
  "Quantity": 2
}

### GET ORDER ITEMS BY USER EMAIL

GET {{baseUrl}}{{route}}
Authorization: Bearer {{userToken}}

### DELETE ALL ORDER ITEMS BY USER EMAIL

DELETE {{baseUrl}}{{route}}/delete
Authorization: Bearer {{userToken}}