# @name Using development environment
# @environment development

@baseUrl = http://localhost:5076/
@route = api/user/orders
@userToken = {{$dotenv USER_TOKEN}}
###

POST {{baseUrl}}{{route}}/create
Content-Type: application/json
Authorization: Bearer {{userToken}}

{
  "ShippingAddress": "1234 Street Name, City, Country",
  "BillingAddress": "1234 Billing Address, City, Country",
  "PaymentMethod": 1
}


### GET ORDERS BY USER EMAIL

GET {{baseUrl}}{{route}}/orders
Authorization: Bearer {{userToken}}

### DELETE ORDER BY USER EMAIL

DELETE {{baseUrl}}{{route}}/cancel-order
Authorization: Bearer {{userToken}}