# @name Using development environment
# @environment development

@baseUrl = http://localhost:5076/
@route = api/user/orders
@userToken = {{$dotenv USER_TOKEN}}


### CREATE ORDER

POST {{baseUrl}}{{route}}/create
Content-Type: application/json
Authorization: Bearer {{userToken}}

{
  "ShippingAddress": "1234 Street Name, City, Country",
  "BillingAddress": "1234 Billing Address, City, Country",
  "PaymentMethod": 1
}

### CANCEL ORDER

POST {{baseUrl}}{{route}}/cancel
Authorization: Bearer {{userToken}}


### GET ORDERS

GET {{baseUrl}}{{route}}
Authorization: Bearer {{userToken}}


