@baseUrl = http://localhost:5076/
@route = api/v1/user/basket

### CREATE ORDER ITEM
POST {{baseUrl}}{{route}}/create
Content-Type: application/json
Authorization: Bearer {{USER_TOKEN}}

{
  "ProductId": 1,
  "Quantity": 15
}

### UPDATE ORDER ITEM
PUT {{baseUrl}}{{route}}/update
Content-Type: application/json
Authorization: Bearer {{USER_TOKEN}}

{
  "BasketItemId": 1,
  "ProductId": 1,
  "Quantity": 2
}

### GET ORDER ITEMS BY USER EMAIL

GET {{baseUrl}}{{route}}
Authorization: Bearer {{USER_TOKEN}}

### DELETE ALL ORDER ITEMS BY USER EMAIL

DELETE {{baseUrl}}{{route}}/delete
Authorization: Bearer {{USER_TOKEN}}