# @name Using development environment
# @environment development

@baseUrl = http://localhost:5076/
@route = api/user/orders
@userToken = {{$dotenv USER_TOKEN}}


### CREATE ORDER

POST {{baseUrl}}{{route}}/create
Content-Type: application/json
Authorization: Bearer {{userToken}}

{
  "CardHolderName": "User",
  "CardNumber": "4111111111111129", // Kart bakiyesi yetersiz senaryosu için test kartı - https://github.com/iyzico/iyzipay-dotnet
  "ExpirationMonth": "12",
  "ExpirationYear": "2029",
  "CVC": "123",
  "RegisterCard": 0
}

### CANCEL ORDER

POST {{baseUrl}}{{route}}/cancel
Authorization: Bearer {{userToken}}


### GET ORDERS

GET {{baseUrl}}{{route}}
Authorization: Bearer {{userToken}}


