@baseUrl = http://localhost:5076

### GET ALL PRODUCTS

GET {{baseUrl}}/api/user/products
Authorization: Bearer {{USER_TOKEN}}

### GET PRODUCT BY ID

GET {{baseUrl}}/api/user/products/1
Authorization: Bearer {{USER_TOKEN}}

