@baseUrl = http://localhost:5076
@resource = users

###
POST {{baseUrl}}/{{resource}}
Content-Type: application/json

{
    "username": "user1",
    "password": "password1",
    "email": "user1@example.com",
    "firstName": "John",
    "lastName": "Doe",
    "phoneNumber": "1234567890"
}

###
GET {{baseUrl}}/{{resource}}

###
GET {{baseUrl}}/{{resource}}/1
    
###
PUT {{baseUrl}}/{{resource}}/1
Content-Type: application/json

{
    "username": "user1",
    "password": "password1",
    "email": "user1@example.com"
}

###
DELETE {{baseUrl}}/{{resource}}/1