@baseUrl = http://localhost:5076
@route = api/v1/user/products
@USER_TOKEN = {{$dotenv USER_TOKEN}}
### GET ALL PRODUCTS

GET {{baseUrl}}/{{route}}
Authorization: Bearer {{USER_TOKEN}}

### GET PRODUCT BY ID

GET {{baseUrl}}/{{route}}/1
Authorization: Bearer {{USER_TOKEN}}

### SEARCH PRODUCTS
GET {{baseUrl}}/{{route}}/search?query=meta
Authorization: Bearer {{USER_TOKEN}}

