@baseUrl = http://localhost:5076

###
POST {{baseUrl}}/api/account/register
Content-Type: application/json

{
    "fullName": "Mehmet Can Ari",
    "email": "blabla@gmail.com",
    "password": "12345678",
    "address": "123 Main St, Anytown, USA",
    "phoneNumber": "1234567890",
    "dateOfBirth": "1999-03-24"
}

###
PUT {{baseUrl}}/api/account/update/1
Content-Type: application/json

{
    "fullName": "Mehmet Can Ari",
    "email": "bsn.mehmetcanari@gmail.com",
    "password": "12345678",
    "address": "Istanbul, Turkey",
    "phoneNumber": "1234567890"
}