@baseUrl = http://localhost:5076
@route = api/auth

### CREATE USER ACCOUNT

POST {{baseUrl}}/{{route}}/create-user
Content-Type: application/json

{
    "fullName": "MEHMET",
    "email": "MEHMET@gmail.com",
    "password": "1exdsadsample@PssordMEMO@",
    "address": "Istanbul, TR",
    "phoneNumber": "1234567890",
    "dateOfBirth": "1909-03-24"
}

### CREATE ADMIN ACCOUNT

POST {{baseUrl}}/{{route}}/create-admin
Content-Type: application/json

{
    "fullName": "Admin User",
    "email": "admin@example.com",
    "password": "AdminPassword123!",
    "address": "Ankara, TR",
    "phoneNumber": "9876543210",
    "dateOfBirth": "1980-01-01"
}

### LOGIN USER ACCOUNT
# @name loginUser
POST {{baseUrl}}/{{route}}/login
Content-Type: application/json

{
  "email": "MEHMET@gmail.com",  
  "password": "1exdsadsample@PssordMEMO@"
}

### LOGIN ADMIN ACCOUNT
# @name loginAdmin
POST {{baseUrl}}/{{route}}/login
Content-Type: application/json

{
  "email": "admin@example.com",  
  "password": "AdminPassword123!"
}

### REFRESH TOKEN USER

POST {{baseUrl}}/{{route}}/refresh-token
