@baseUrl = http://localhost:5076/
@route = api/user/order-items
@userToken =  {{$dotenv USER_TOKEN}}

### CREATE ORDER ITEM
POST {{baseUrl}}{{route}}/create
Content-Type: application/json
Authorization: Bearer {{userToken}}

{
  "AccountId": 1,
  "ProductId": 1,
  "Quantity": 1
}

### UPDATE ORDER ITEM
PUT {{baseUrl}}{{route}}/update
Content-Type: application/json
Authorization: Bearer {{userToken}}

{
  "OrderItemId": 1,
  "AccountId": 1,
  "ProductId": 1,
  "Quantity": 2
}

### GET ORDER ITEMS BY USER ID

GET {{baseUrl}}{{route}}
Authorization: Bearer {{userToken}}

### DELETE ALL ORDER ITEMS BY USER ID

DELETE {{baseUrl}}{{route}}/delete/1
Authorization: Bearer {{userToken}}
