@baseUrl = http://localhost:5076
@resource = orderitems

###
POST {{baseUrl}}/{{resource}}
Content-Type: application/json

{
    "quantity": 1,
    "product": {
        "id": 1
    }
}

###
GET {{baseUrl}}/{{resource}}

###

GET {{baseUrl}}/{{resource}}/1

###
PUT {{baseUrl}}/{{resource}}/1
Content-Type: application/json

{
    "quantity": 2,
    "product": {
        "id": 1
    }
}

###
DELETE {{baseUrl}}/{{resource}}/1