@baseUrl = http://localhost:5076

###

GET {{baseUrl}}/api/admin/products

###

GET {{baseUrl}}/api/admin/products/1

###

POST {{baseUrl}}/api/admin/products/create
Content-Type: application/json

{
  "Name": "Playstation 5",
  "Description": "A game console from Sony",
  "Price": 399.99,
  "ImageUrl": "exampleURL",
  "StockQuantity": 50
}

###

PUT {{baseUrl}}/api/admin/products/update/1
Content-Type: application/json

{
  "Name": "Gaming PC",
  "Description": "High-end gaming PC",
  "Price": 2399.99,
  "ImageUrl": "exampleURL",
  "StockQuantity": 3
}

###

DELETE {{baseUrl}}/api/admin/products/delete/1